category: Routing
questions:
    -
        question: 'Using XML or YAML, how to declare a route for a specific domain/host?'
        answers:
            - {value: Add a "domain" attribute,    correct: false}
            - {value: Add a "host" attribute,      correct: true}
            - {value: Add a "path" attribute,      correct: false}
            - {value: Add a "subdomain" attribute, correct: false}
    -
        question: 'What variable can be used as controller argument to get the name of the route name?'
        answers:
            - {value: $_route,            correct: true}
            - {value: $_controller,       correct: false}
            - {value: $_method,           correct: false}
            - {value: $_action,           correct: false}
    -
        question: 'Using XML, how to ensure that a route is accessed via HTTPS?'
        answers:
            - {value: schemes="https",  correct: true}
            - {value: https="true",     correct: false}
            - {value: protocol="https", correct: false}
            - {value: ensure="https",   correct: false}
    -
        question: 'Three special routing parameters are available in Symfony:'
        answers:
            - {value: "_controller, _locale, _schemes",      correct: false}
            - {value: "_route, _controller, _action",        correct: false}
            - {value: "_controller, _locale, _format",       correct: true}
            - {value: "_locale, _format and another one.",   correct: false}
