category: Security
questions:
    -
        question: 'Which line is correct to add a security.access_control line?'
        answers:
            - {value: "- { path: ^/admin, roles: ROLE_ADMIN }", correct: true}
            - {value: "- { path: ^/admin, acl: ROLE_ADMIN }",   correct: false}
            - {value: "- { url: ^/admin, roles: ROLE_ADMIN }",  correct: false}
            - {value: "- { url: ^/admin, acl: ROLE_ADMIN }",    correct: false}
    -
        question: 'After a login success, what is the parameter name to redirect on referer URL?'
        answers:
            - {value: security.firewalls.<name>.form_login.use_referer,         correct: true}
            - {value: security.firewalls.<name>.form_login.after_login_referer, correct: false}
            - {value: security.firewalls.<name>.form_login.referer,             correct: false}
            - {value: security.firewalls.<name>.form_login.success_referer,     correct: false}
    -
        question: 'In Symfony Security component:'
        answers:
            - {value: 'Symfony\Bundle\SecurityBundle\Security\FirewallContext services are publicly created that correspond to each context you create under your security.yml, a context is called an authenticator', correct: false}
            - {value: 'Symfony\Bundle\SecurityBundle\Security\FirewallContext services are privately created that correspond to each context you create under your security.yml, a context is also known as per each firewall', correct: false}
            - {value: 'Symfony\Bundle\SecurityBundle\Security\FirewallContext services are synthetically created that correspond to each context you create under your security.yml, each context is liked to an authenticator', correct: false}
            - {value: 'Symfony\Bundle\SecurityBundle\Security\FirewallContext services are publicly created that correspond to each context you create under your security.yml, a context is related to each FirewallContext directly but is overall handled by a generic Symfony\Bundle\SecurityBundle\Security\Firewall object', correct: true}
    -
        question: 'In Symfony Security component:'
        answers:
            - {value: 'SecureRandom class at the heart of security component has only one public nextBytes method', correct: true}
            - {value: 'RoleHierarchy also at the heart of security component implements RoleHierarchyInterface which obliges this class to implement buildRoleMap', correct: false}
            - {value: 'There are only two classes named ResponseListener in the whole of Symofony and they implement EventSubscriberInterface', correct: true}
            - {value: 'There is a ResponseListener under RememberMe feature and this acts by setting a cookie on every response the app sends back to the user', correct: false}
            - {value: 'About the other ResponseListener found under HttpKernel complaint with RFC 2616 means most importantly that it ensures certain dimensions on header length are kept', correct: false}
            - {value: 'in Symfony Symfony\Component\Security\Core\Encoder\EncoderFactory getEncoder does create an encoder everytime for security reasons', correct: false}
